
development:
  adapter: mysql2
  database: dev_db1
  username: root
  password: 

test:
  adapter: mysql2
  database: test_db
  username: root
  password: 

production:
  adapter: mysql2
  database: prd_db
  username: root
  password: 
 
